### ISSUE TITLE
On Windows, "#writeStyle" tests fail

### ISSUE THREAD

**Issue by pprev94** [geostyler/geostyler-qgis-parser#339]
On Windows :
- When reading QML file, linebreaks are \r\n
- When writing style, linebreaks are \n only

To fix it, I suggest in function writeStyle of QGISStyleParser class

```
let renderOpts = { pretty: true, indent: '  ', newline: '\n' };
if ('win32' === process.platform) {
  renderOpts.newline = '\r\n'; 
}

return new Promise<WriteStyleResult<string>>(resolve => {
  try {
	const builder = new Builder({ renderOpts: renderOpts });
...
```

Is there a better way to do it ?

**Comment by KaiVolland** [comment]
Hey @pprev94. Thanks for the report.

Would be cool if we could keep this in sync with the SLD-Parser: https://github.com/geostyler/geostyler-sld-parser/blob/master/src/SldStyleParser.ts#L1303

We have an  `prettyOutput` option over there. Could you check if this would fix it for you?

**Comment by pprev94** [comment]
I've the same errors in SLD parser too
prettyOutput is not enough, we need to define newline characters to '\r\n' for windows

**Comment by KaiVolland** [comment]
Ohh ok. Maybe there is a way to fix this issue within the testsuite instead of a change to the parser. I don't know when i'll find time to have a closer look at this.

**Comment by pprev94** [comment]
May I suggest to remove the character '\r'    

`const qml = fs.readFileSync('./data/qmls/no_symbolizer.qml', 'utf8').replace(/\r/g, "")`

Now tests run correctly

**Comment by KaiVolland** [comment]
I'll have a look at this later.

**Comment by KaiVolland** [comment]
What surprises me is that the linebreak when **reading** the file can be different. I thought this information would be stored in the file.
Lineending should be LF (`\n`) for all qml files.
 :thinking:

**Comment by KaiVolland** [comment]
> Lineending should be LF (`\n`) for all qml files.

If this is not the case for you @pprev94 . We may need to add a `.gitattributes` file to force LF (`\n`) when checking out:

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#example
