### ISSUE TITLE
build failed (on windows)

### ISSUE THREAD

**Issue by pprev94** [geostyler/geostyler-qgis-parser#340]
# Bug

npm run build fails on windows (not sure if it's related to os)

Error message is 
`
ERROR in ./src/QGISStyleParser.ts 30:5
Module parse failed: Unexpected token (30:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import _get from 'lodash/get';
|
> type SymbolizerMap = {
|   [key: string]: Symbolizer[]
| };
 @ multi ./src/QGISStyleParser.ts main[0]
`

**Comment by jansule** [comment]
Thanks for the info @pprev94! I just checked [current master](https://github.com/geostyler/geostyler-qgis-parser/tree/846b761cb83f6c4c487e2ef6607641b7128ac07d) and it works for me on linux. So this might be an OS problem, indeed.

Did you already find a fix/workaround for your setup?

**Comment by ocruze** [comment]
Ok, after long debugging, it was an easy solution after all, just a small problem with path resolution on windows:

```diff
  module: {
      rules: [{
        test: /\.ts$/,
--      include: __dirname + '/src',
++      include: /src/,
        use: [{
          loader: require.resolve('ts-loader'),
        }]
      }]
    }
```

Tested on my wsl Ubuntu, this change does not break the build on Linux environment.

**Comment by jansule** [comment]
You might have to make use of the `path` lib, to solve this problem. See for example here: https://github.com/geostyler/geostyler/blob/main/webpack.dev.config.js#L50
