### ISSUE TITLE
Capitalized invalid WellKnownName value for mark symbolizer

### ISSUE THREAD

**Issue by raitisbe** [geostyler/geostyler-qgis-parser#379]
# Bug

**Describe the bug**
Well known name of circle gets capitalized unnecessarily resulting in invalid WellKnownName in geostyler style object - "Circle" insted of "circle", which makes OlStyleParser fail in turn.

**To Reproduce**
1. Parse qml http://hub4everybody.lesprojekt.cz/rest/workspaces/franta/layers/bioregions_pilots/style (it has correct value "circle")
2. Observe resulting style object:
![image](https://user-images.githubusercontent.com/395514/194837174-60dc5ad5-2a25-47b5-b2c1-16908d8f19d2.png) with value "Circle"
3. Since OlStyleParser is case sensitive to WellKnowName values, it would fail with:
![image](https://user-images.githubusercontent.com/395514/194837444-e647733d-3563-4329-b034-0c39152d5d83.png)

**Expected behavior**
WellKnownName property should be lowercased. Probably in https://github.com/geostyler/geostyler-qgis-parser/blob/master/src/QGISStyleParser.ts#L493

**Screenshots**
![image](https://user-images.githubusercontent.com/395514/194836018-9216530f-3413-4fff-aef8-3ab14e32449d.png)

**Desktop (please complete the following information):**
 - OS: arch
 - Browser chrome

**Additional context**

geostyler-qgis-parser@1.0.0

Related bug in hslayers https://github.com/hslayers/hslayers-ng/issues/3431

**Comment by jansule** [comment]
Good point @raitisbe. According to the latest geostyler-style specification, WellKnownName should be lowercase. See https://github.com/geostyler/geostyler-style/blob/master/style.ts#L174

Are you planning on providing a PR for that?

**Comment by KaiVolland** [comment]
This should be fixed with the latest release.

**Comment by raitisbe** [comment]
thank you
