### ISSUE TITLE
Is it possible to use raster QML style?

### ISSUE THREAD

**Issue by aborruso** [geostyler/geostyler-qgis-parser#492]
Hi,
as I written [here](https://github.com/geostyler/geostyler-cli/issues/359), I would like to use geostyler for this [this qml](https://gist.github.com/aborruso/cb0f539fc48f559e48010b5e7419bf4e) style.

But it does not seem supported. Do you confirm it?

If yes, this is a feature request.

Thank you for this great tool

**Comment by KaiVolland** [comment]
Hey @aborruso :wave:,

unfortunately the QGIS parser is one of the least grown parsers. Usually there is an `unsupportedProperties` attribute in the parsers that gives information about what is supported and what is not.

I quickly checked the code and it seems like RasterStyles are not supported by the parser.

I am also afraid that we don't have the capacity to add this support in the near future as we're currently bound to other parts of the geostyler ecosystem.

The greatest thing would be to provide a PR that solves this problem. But I think the barrier to entry for coding the qml parser is pretty high.

**Comment by aborruso** [comment]
I'm not able to open this kind of PR.

Thank you
