### ISSUE TITLE
Error when converting QML: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by max-mapper** [geostyler/geostyler-qgis-parser#541]
# Bug

**Describe the bug**
I receive this error:

```
$ node -v
v20.14.0
$ geostyler -v
v3.0.0
$ geostyler -s qgis -t mapbox -o calveg-ec-clipped.json calveg-ec-clipped.qml 
✖ Error during translation of file "calveg-ec-clipped.qml": TypeError: Cannot read properties of undefined (reading 'forEach')
```

**To Reproduce**

[calveg-ec-clipped.zip](https://github.com/user-attachments/files/15520575/calveg-ec-clipped.zip)

This QML file exported from QGIS using 3.36.3-Maidenhead

Also worth noting... if I export the same layer in QGIS to SLD and then convert SLD to Mapbox, it does not include the fill values. However, if I export from QGIS to SLD, then use geostyler to convert SLD to QML and then QML to Mapbox, it includes fill values. Hence this is why I am reporting this issue, it would be nice if QML worked without crashing. It would also be nice if QGIS exported SLD converted directly to Mapbox and included fill values

**Comment by KaiVolland** [comment]
Hey @max-mapper, thanks for the report. I'll add it to the codes-print board. Maybe someone will have the time to have a look at it.

**Comment by geographika** [comment]
This is the same issue as #455 and #540, with the development fix branch at https://github.com/geostyler/geostyler-qgis-parser/compare/master...OSHistory:geostyler-qgis-parser:readQGIS228

It looks like there were major changes to the (undocumented) QML structures from QGIS 3.28 onwards. 

See https://github.com/qgis/QGIS/pull/45143 and https://github.com/qgis/QGIS/pull/40716

@geostyler/sprinters I think we should probably add a warning to the README.md that the parser only works with pre QGIS 3.28 versions until fixed.
